services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - my_network

  my_api:
    build: .
    container_name: myuserapi
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    networks:
      - my_network
    depends_on:
      - mssql

networks:
  my_network:
    driver: bridge

volumes:
  mssql-data:
